const translate = [
    'Tornado',
    'Tempestade Tropical',
    'Furacões',
    'Tempestade Severa',
    'Tempestade',
    'Chuva e Neve',
    'Chuva e Granizo',
    'Neve e Granizo',
    'Garoa',
    'Garoa',
    'Chuva ',
    'Chuva',
    'Chuva',
    'Rajada de Neve',
    'Neve Fraca',
    'Neve',
    'Granizo',
    'Granizo',
    'Poeira',
    'Nebuloso',
    'Neblina',
    'Esfumaçado',
    'Tempestade',
    'Ventoso',
    'Frio',
    'Nublado',
    'Noite Nublada',
    'Dia Nublado',
    'Parcialmente Nublado',
    'Noite',
    'Ensolarado',
    'Limpo',
    'Limpo',
    'Chuva e Granizo',
    'Quente',
    'Tempestade',
    'Tempestade',
    'Chuva Dispersa',
    'Chuva Forte',
    'Neve',
    'Neve',
    'Nevasca',
    'Chuva',
    'Neve',
    'Aguaceiro'
];

export default translate;